#!/usr/bin/env node
require('babel-core/register')({
  ignore: /node_modules(?!\/contentful-resolve-response)/
})
require('require-all')({
  dirname: process.cwd() + '/test/unit',
  filter: process.argv[2] || /-test\.js$/,
  recursive: true
})
