#!/usr/bin/env node
require('regenerator-runtime/runtime')
require('@babel/register')({
  ignore: [/node_modules(?!\/contentful-resolve-response)/]
})
require('require-all')({
  dirname: process.cwd() + '/test/unit',
  filter: process.argv[2] || /-test\.js$/,
  recursive: true
})
